add uat deploy

diff --git a/.github/workflows/uat_backend_deplpy.yaml b/.github/workflows/uat_backend_deplpy.yaml
--- a/.github/workflows/uat_backend_deplpy.yaml
+++ b/.github/workflows/uat_backend_deplpy.yaml
@@ -44,3 +44,10 @@ jobs:
           git commit -m "Update backend-${SERVICE}.yaml to ${VERSION}"
           git push origin uat
 
+          
+      - name: Run UAT test for backend service
+        run: |
+          URL="http://uat.zhunandomain.live/${SERVICE}"
+          echo "Running UAT test on: $URL"
+          curl --fail --retry 3 --retry-delay 5 "$URL" || (echo "UAT test failed for $SERVICE" && exit 1)
+
diff --git a/.github/workflows/uat_frontend_deploy.yaml b/.github/workflows/uat_frontend_deploy.yaml
--- a/.github/workflows/uat_frontend_deploy.yaml
+++ b/.github/workflows/uat_frontend_deploy.yaml
@@ -37,4 +37,9 @@ jobs:
           git add frontend-client.yaml
           git commit -m "Update frontend-client.yaml to ${VERSION}"
           git push origin uat
-
+          
+      - name: Run UAT test for frontend
+        run: |
+          URL="http://uat.zhunandomain.live/"
+          echo "Running UAT test on: $URL"
+          curl --fail --retry 3 --retry-delay 5 "$URL" || (echo "UAT test failed for frontend" && exit 1)
